#!/usr/bin/env php
<?php

// check installation [composer default, composer bin, git clone]
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
    if (file_exists($file)) {
        define('HEVELOPHOOK_COMPOSER_AUTOLOAD', $file);
    }
}
unset($file);

if (!defined('HEVELOPHOOK_COMPOSER_AUTOLOAD')) {
    fwrite(STDERR,
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

require HEVELOPHOOK_COMPOSER_AUTOLOAD;

$app = new HevelopHookManager\App\Console\Application\HevelopSetup();
$app->run();
